config/routes.rb
Rails.application.routes.draw do
  root "gifs#index"
  resources :gifs
  devise_for :users
end

app/models/gif.rb
class Gif < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_action :set_gif, only: [:show, :edit, :update, :destroy]

  # GET /gifs
  # GET /gifs.json
  def index
    @gifs = Gif.all
  end

  # GET /gifs/1
  # GET /gifs/1.json
  def show
  end

  # GET /gifs/new
  def new
    @gif = Gif.new
    image = Giphy.random
    random_id = image.id
    random_url = image.image_original_url
    @gif.gif_id = random_url
  end

  # GET /gifs/1/edit
  def edit

  end

  # POST /gifs
  # POST /gifs.json
  def create
    @gif = Gif.new(gif_params)
    @gif.user = current_user.id
    respond_to do |format|
      if @gif.save
        format.html { redirect_to @gif, notice: 'Gif was successfully created.' }
        format.json { render :show, status: :created, location: @gif }
      else
        format.html { render :new }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifs/1
  # PATCH/PUT /gifs/1.json
  def update
    respond_to do |format|
      if @gif.update(gif_params)
        format.html { redirect_to @gif, notice: 'Gif was successfully updated.' }
        format.json { render :show, status: :ok, location: @gif }
      else
        format.html { render :edit }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1
  # DELETE /gifs/1.json
  def destroy
    @gif.destroy
    respond_to do |format|
      format.html { redirect_to gifs_url, notice: 'Gif was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gif
      @gif = Gif.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gif_params
      params.require(:gif).permit(:user, :feeling, :gif_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/views/gifs/_form.html.erb
<%= form_for(@gif) do |f| %>
  <% if @gif.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gif.errors.count, "error") %> prohibited this gif from being saved:</h2>

      <ul>
      <% @gif.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feeling %><br>
    <%= f.text_field :feeling %>
  </div>
  <div class="field">
    <%= f.label :gif_id %><br>
    <%= f.text_field :gif_id, :value => @gif.gif_id  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gifs/_random_gif.html.erb
<h1>So how do you feel about this .gif?</h1>
  <%= image_tag "#{@gif.gif_id}" , class: "center-block" %>
</div>

app/views/gifs/edit.html.erb
<h1>Editing Gif</h1>

<%= render 'form' %>

<%= link_to 'Show', @gif %> |
<%= link_to 'Back', gifs_path %>

app/views/gifs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="jumbotron">
    <% unless user_signed_in? %>
      <%= link_to "Sign-Up", new_user_registration_path %>
    <% else %>
      <%= link_to "Get your next gif and leave a feeling", new_gif_path , class: "btn btn-primary btn-lg" %>
    <% end %>
</div>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Feeling</th>
      <th>Gif</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifs.each do |gif| %>
      <tr>
        <h1>So how do you feel about this .gif?</h1>
          <%= image_tag "#{gif.gif_id}" , class: "center-block" %>
        </div>
        <td><%= gif.user %></td>
        <td><%= gif.feeling %></td>
        <td><%= link_to 'Show', gif %></td>
        <td><%= link_to 'Edit', edit_gif_path(gif) %></td>
        <td><%= link_to 'Destroy', gif, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gif', new_gif_path %>

app/views/gifs/new.html.erb
<%= render "random_gif" %>

<%= render 'form' %>

<%= link_to 'Back', gifs_path %>

app/views/gifs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @gif.user %>
</p>

<p>
  <strong>Feeling:</strong>
  <%= @gif.feeling %>
</p>

<p>
  <strong>Gif:</strong>
  <%= @gif.gif_id %>
</p>

<%= link_to 'Edit', edit_gif_path(@gif) %> |
<%= link_to 'Back', gifs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NirdExampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path do %>
        <%= image_tag "nird_logo_centered.png" %>
      <% end %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sign in", new_user_session_path %></li>
    </ul>
  </div>
</nav>
<%= yield %>
</body>
</html>